Add rdbms matrix for wider compatibility testing
friends-of-reactphp/mysql pull request #196
Opened 2024-03-21 20:40 UTC by WyriHaximus

This change set introduces a `rdbms` matrix with the purpose of increasing insurance this package works with up to the latest MySQL/MariaDB versions.

2024-04-19 11:04 UTC, SimonFrings reviewed
Interesting approach, but I'm not sure if we should add this to the same MySQL job here. You suggested to test this with `mariadb:10` across all supported PHP versions, but I don't think this is necessary here. Looking further, if we want to support additional databases in different versions, this would result in a huge (and completely confusing) test matrix in GitHub actions.

I think we should test `mysql` across all supported PHP versions, but for `mariadb` we could also test against the latest PHP version(s) in a different job to avoid overloading this.

What do you think?

2024-04-22 20:29 UTC, WyriHaximus commented
> Interesting approach, but I'm not sure if we should add this to the same MySQL job here. You suggested to test this with `mariadb:10` across all supported PHP versions, but I don't think this is necessary here. Looking further, if we want to support additional databases in different versions, this would result in a huge (and completely confusing) test matrix in GitHub actions.

We could introduce MariaDB in a follow up PR.

> I think we should test `mysql` across all supported PHP versions, but for `mariadb` we could also test against the latest PHP version(s) in a different job to avoid overloading this.

Givin that MariaDB is a fork by the creator on MySQL, we could flip a could and prefer one of them?

> What do you think?

To be brutally honest: Test all permutations; but that is a personal preference that I enforce in my own packages and projects, so I'll make the adjustment for this PR.

2024-04-23 13:11 UTC, WyriHaximus commented
@SimonFrings Pushed the changes

2025-05-21 16:21 UTC, clue requested changes

2025-05-21 16:21 UTC, clue commented on .github/workflows/ci.yml
> +    name: PHPUnit (PHP ${{ matrix.php }}; RDBMS ${{ matrix.rdbms }})
Nit: Job title should be shortened:

![Screenshot 2025-05-21 at 18-19-35 Add rdbms matrix for wider compatibility testing by WyriHaximus · Pull Request #196 · friends-of-rea](https://github.com/user-attachments/assets/11cb2098-3395-43cf-a3fa-4fd38d85596c)



```suggestion
    name: PHPUnit (PHP ${{ matrix.php }} + ${{ matrix.rdbms }})
```

2025-05-21 16:28 UTC, WyriHaximus commented on .github/workflows/ci.yml
> +    name: PHPUnit (PHP ${{ matrix.php }}; RDBMS ${{ matrix.rdbms }})
Yup that looks a whole lot better: 
![image](https://github.com/user-attachments/assets/f3e66fdf-91f1-4855-946d-191e51036315)

2025-05-21 16:30 UTC, clue approved these changes
@WyriHaximus Thanks for looking into this, changes LGTM! :shipit: 

Especially useful once #207 is merged for MySQL 8 and MySQL 9 support! :tada:

2025-05-21 16:30 UTC, merged

2025-05-21 16:32 UTC, WyriHaximus commented
@clue Cheers, having a look at 206 and 207 in the next hour 👍